### ISSUE TITLE
API Guidelines tracking issue

### ISSUE THREAD

**Issue by sebasmagri** [sebasmagri/env_logger#5]
From https://public.etherpad-mozilla.org/p/rust-api-guidelines-env_logger.

- [x] [Implement missing `impl`s for `Target`](https://github.com/sebasmagri/env_logger/issues/6)
- [x] [Define and implement missing traits for `Logger`](https://github.com/sebasmagri/env_logger/issues/7)
- [x] [Add missing rustdoc examples to `Logger::new` and `Logger::filter`](https://github.com/sebasmagri/env_logger/issues/8)
- [x] [Remove `unwrap` from examples](https://github.com/sebasmagri/env_logger/issues/9)
- [x] [Add missing info to _Errors_ and _Panics_ documentation section](https://github.com/sebasmagri/env_logger/issues/10)
- [x] [Make references to `log` be hyperlinks](https://github.com/sebasmagri/env_logger/issues/11)
- [x] [Update `Cargo.toml` with `readme` and new links](https://github.com/sebasmagri/env_logger/issues/12)
- [x] [Should we add `filter_module` and `filter_level` as separate functions to `Builder`?](https://github.com/sebasmagri/env_logger/issues/13)
- [x] [Implement `Debug` for `Logger` and `Filter`](https://github.com/sebasmagri/env_logger/issues/14)
